version: '2'
services:

  elasticsearch-master:
    scale: {{elasticsearch_master_scale}}
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9200
      unhealthy_threshold: 3
      initializing_timeout: 180000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 180000
    metadata:
      elasticsearch-config: |
{{ lookup('template', elasticsearch_conf_file) | indent(8, True) }}

{% if elasticsearch_plugins_name | length > 0 %}
      elasticsearch-plugins: |
{% for plugin in elasticsearch_plugins_name %}
        {{plugin}}
{% endfor %}
{% endif %}
  elasticsearch-data:
    scale: {{elasticsearch_data_scale}}
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9200
      unhealthy_threshold: 3
      initializing_timeout: 180000
      interval: 2000
      strategy: none
      reinitializing_timeout: 180000
    metadata:
      elasticsearch-config: |
{{ lookup('template', elasticsearch_conf_file) | indent(8, True) }}

{% if elasticsearch_plugins_name | length > 0 %}
      elasticsearch-plugins: |
{% for plugin in elasticsearch_plugins_name %}
        {{plugin}}
{% endfor %}
{% endif %}
  elasticsearch-client:
    scale: {{elasticsearch_client_scale}}
    retain_ip: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 9200
      unhealthy_threshold: 3
      initializing_timeout: 180000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 180000
    metadata:
      elasticsearch-config: |
{{ lookup('template', elasticsearch_conf_file) | indent(8, True) }}

{% if elasticsearch_plugins_name | length > 0 %}
      elasticsearch-plugins: |
{% for plugin in elasticsearch_plugins_name %}
        {{plugin}}
{% endfor %}
{% endif %}
  elasticsearch-setup:
    metadata:
      templates: |
        [
{% for templateFile in elasticsearch_template_files %}
          {
            "name" : "{{templateFile | basename | splitext | first }}",
            "value" :
{{ lookup('template', templateFile) | indent(12, True) }}
          }{% if not loop.last %},{% endif %}
{% endfor %}

        ]

{% if elasticsearch_repository_files | length > 0 %}
      repositories: |
        [
{% for repositoryFile in elasticsearch_repository_files %}
          {
            "name" : "{{repositoryFile  | basename | splitext | first }}",
            "value" :
{{ lookup('template', repositoryFile) | indent(12, True) }}
          }{% if not loop.last %},{% endif %}
{% endfor %}

        ]
{% endif %}

{% if elasticsearch_license_file != "" %}
      license: |
{{ lookup('template', elasticsearch_license_file) | indent(8, True) }}
{% endif %}

  elasticsearch-prometheus-exporter:
    scale: 1
    start_on_create: true
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 7979
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000

  curator:
    metadata:
      curator-actions: |
{{ lookup('template', curator_config_file) | indent(8, True) }}
