version: '2'
services:
  kafka-jmx-exporter:
    labels:
      io.rancher.container.start_once: 'true'
    image: adopteunops/prometheus-jmx-exporter:0.10
    network_mode: none
  kafka:
    ports:
    - 9092:9092/tcp
    environment:
      KAFKA_OFFSETS_RETENTION_MINUTES: 10080
      KAFKA_LOG_RETENTION_HOURS: '168'
      KAFKA_LOG_RETENTION_SIZE: '-1'
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_MAX_REQUEST_SIZE: '10485760'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      #requires hostname to be resolvable
      #HOSTNAME_COMMAND: "curl -s http://rancher-metadata.rancher.internal/latest/self/host/hostname"
      HOSTNAME_COMMAND: "curl -s http://rancher-metadata.rancher.internal/latest/self/host/agent_ip"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "{{kafka_zookeeper_path}}"
      BROKER_ID_COMMAND: "curl -s http://rancher-metadata.rancher.internal/latest/self/container/service_index"
      RACK_COMMAND: "curl -s http://rancher-metadata.rancher.internal/latest/self/host/labels/rack"
      KAFKA_HEAP_OPTS: "-Xms{{kafka_heap_size}} -Xmx{{kafka_heap_size}}"
      KAFKA_LOG_DIRS: "/kafka/kafka-logs"
      KAFKA_OPTS: "-javaagent:/etc/jmx_exporter/jmx_exporter_agent.jar=1234:/etc/jmx_exporter/kafka-0-8-2.yml"
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    external_links:
    - zookeeper/zookeeper:zookeeper
    volumes:
    - kafka-volume:/kafka/kafka-logs
    volumes_from:
    - kafka-jmx-exporter
    labels:
      io.rancher.sidekicks: kafka-jmx-exporter
      io.rancher.container.hostname_override: container_name
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.scheduler.affinity:host_label: role_kafka=true
      com.prometheus.monitoring: true
      com.prometheus.port: 1234
    tty: true
    image: wurstmeister/kafka:2.11-1.1.1
    stdin_open: true

  kafka-manager:
    environment:
      APPLICATION_SECRET: letmein
      ZK_HOSTS: "{{kafka_manager_zookeeper_path}}"
    external_links:
    - zookeeper/zookeeper:zookeeper
    labels:
      io.rancher.container.hostname_override: container_name
    tty: true
    image: hlebalbau/kafka-manager:1.3.3.18
    stdin_open: true
  kafka-manager-setup:
    external_links:
    - zookeeper/zookeeper:zookeeper
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: 'true'
    tty: true
    image: skalogs/kafka-manager-setup:1.0.0
    environment:
      ZK_HOSTS: "{{kafka_zookeeper_path}}"
      KAFKA_VERSION: "1.1.0"
    links:
    - kafka-manager:kafka-manager
    stdin_open: true

  kafka-lag-prometheus-exporter:
    environment:
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    labels:
      io.rancher.container.pull_image: always
      com.prometheus.monitoring: true
      com.prometheus.port: 7979
    tty: true
    image: adopteunops/kafka-lag-prometheus-exporter:1.0-SNAPSHOT
    links:
    - 'kafka:'
    stdin_open: true

volumes:
  kafka-volume:
    per_container: true
